@Library('jenkins-shared-library') _

cicdPipeline(
    repo: 'https://github.com/your-org/notification-service.git',
    imageName: 'your-dockerhub-username/notification-service',
    dockerCreds: 'dockerhub-credentials-id'
)
